/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframe;

import java.awt.*;
import java.awt.event.*;
import java.text.NumberFormat;
import DAO.*;
import UI_Helper.RoundedPanel;
import javax.swing.border.MatteBorder;

/**
 *
 * @author HS
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
        updateTotalBooks();
        updateTotalReaders();
        updateTotalTitles();
        updateTotalReadersBorrowingBooks();
        updateTotalReadersOverdue();       

    }

    private void updateTotalBooks() {
        int totalBooks = StatisticsDAO.getTotalBooks();
        NumberFormat formatter = NumberFormat.getInstance();
        txtNoB.setText(formatter.format(totalBooks));
    }

    private void updateTotalTitles() {
        int totalBooks = StatisticsDAO.getTotalTitles();
        NumberFormat formatter = NumberFormat.getInstance();
        txtNoT.setText(formatter.format(totalBooks));
    }

    private void updateTotalReaders() {
        int totalBooks = StatisticsDAO.getTotalReaders();
        NumberFormat formatter = NumberFormat.getInstance();
        txtNoR.setText(formatter.format(totalBooks));
    }

    private void updateTotalReadersOverdue() {
        int totalBooks = StatisticsDAO.getReadersOverdue();
        NumberFormat formatter = NumberFormat.getInstance();
        txtNoOver.setText(formatter.format(totalBooks));
    }

    private void updateTotalReadersBorrowingBooks() {
        int totalBooks = StatisticsDAO.getReadersBorrowingBooks();
        NumberFormat formatter = NumberFormat.getInstance();
        txtNoBR.setText(formatter.format(totalBooks));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnMR = new rojerusan.RSButtonHover();
        btnBBF = new rojerusan.RSButtonHover();
        btnMP = new rojerusan.RSButtonHover();
        btnMB = new rojerusan.RSButtonHover();
        btnStatistics = new rojerusan.RSButtonHover();
        jPanel7 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtNoT = new javax.swing.JTextField();
        lblNoB = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        lblNoB1 = new javax.swing.JLabel();
        txtNoB = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        lblNoR = new javax.swing.JLabel();
        txtNoR = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        lblNoR1 = new javax.swing.JLabel();
        txtNoOver = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        lblNoR2 = new javax.swing.JLabel();
        txtNoBR = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        btnLOGOUT = new rojerusan.RSButtonHover();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICTURE_icon/li4.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 41, -1));

        jPanel1.setBackground(new java.awt.Color(102, 102, 0));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 6, 3, 35));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("LIBRARY MANAGEMENT SYSTEM");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 15, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, 50));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setBackground(new java.awt.Color(0, 51, 51));
        jPanel13.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 0, 0, 0, new java.awt.Color(255, 255, 255)));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(102, 153, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICTURE_icon/home.png"))); // NOI18N
        jLabel4.setText("HOME PAGE");
        jLabel4.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 0, 0, 0, new java.awt.Color(255, 255, 255)));
        jPanel13.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 170, 50));

        jPanel4.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, -1));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("DASHBOARD");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 180, 39));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 51, 200, -1));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICTURE_icon/home_24px.png"))); // NOI18N
        jLabel8.setText("HOME PAGE");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, -1, 39));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Features");
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 39));

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 96, 200, 39));

        btnMR.setBackground(new java.awt.Color(255, 255, 255));
        btnMR.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        btnMR.setForeground(new java.awt.Color(0, 51, 51));
        btnMR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICTURE_icon/book-reader.png"))); // NOI18N
        btnMR.setText("   Manage  Readers");
        btnMR.setColorHover(new java.awt.Color(204, 0, 51));
        btnMR.setColorText(new java.awt.Color(0, 51, 51));
        btnMR.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMRActionPerformed(evt);
            }
        });
        jPanel4.add(btnMR, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 200, -1));

        btnBBF.setBackground(new java.awt.Color(255, 255, 255));
        btnBBF.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        btnBBF.setForeground(new java.awt.Color(0, 51, 51));
        btnBBF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICTURE_icon/online-survey.png"))); // NOI18N
        btnBBF.setText("   Manage Borrow Slips");
        btnBBF.setColorHover(new java.awt.Color(204, 0, 51));
        btnBBF.setColorText(new java.awt.Color(0, 51, 51));
        btnBBF.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBBF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBBFActionPerformed(evt);
            }
        });
        jPanel4.add(btnBBF, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 200, -1));

        btnMP.setBackground(new java.awt.Color(255, 255, 255));
        btnMP.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        btnMP.setForeground(new java.awt.Color(0, 51, 51));
        btnMP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICTURE_icon/punishment.png"))); // NOI18N
        btnMP.setText(" Manage Penalties");
        btnMP.setColorHover(new java.awt.Color(204, 0, 51));
        btnMP.setColorText(new java.awt.Color(0, 51, 51));
        btnMP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMPActionPerformed(evt);
            }
        });
        jPanel4.add(btnMP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 200, -1));

        btnMB.setBackground(new java.awt.Color(255, 255, 255));
        btnMB.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        btnMB.setForeground(new java.awt.Color(0, 51, 51));
        btnMB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICTURE_icon/knowledge.png"))); // NOI18N
        btnMB.setText("       Manage Books");
        btnMB.setToolTipText("");
        btnMB.setColorHover(new java.awt.Color(204, 0, 51));
        btnMB.setColorText(new java.awt.Color(0, 51, 51));
        btnMB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMBActionPerformed(evt);
            }
        });
        jPanel4.add(btnMB, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, -1, -1));

        btnStatistics.setBackground(new java.awt.Color(255, 255, 255));
        btnStatistics.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        btnStatistics.setForeground(new java.awt.Color(0, 51, 51));
        btnStatistics.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICTURE_icon/pie-chart.png"))); // NOI18N
        btnStatistics.setText("         View Statistic");
        btnStatistics.setColorHover(new java.awt.Color(204, 0, 51));
        btnStatistics.setColorText(new java.awt.Color(0, 51, 51));
        btnStatistics.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnStatistics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatisticsActionPerformed(evt);
            }
        });
        jPanel4.add(btnStatistics, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, -1, -1));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, -1));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 0, 0, 0, new java.awt.Color(255, 255, 255)));
        jPanel9.setOpaque(false);
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(0, 51, 51));
        jPanel10.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        RoundedPanel jPanel10 = new RoundedPanel(30);
        jPanel10.setBackground(new Color(255, 255, 255));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICTURE_icon/book-stack2.png"))); // NOI18N
        jPanel10.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        txtNoT.setEditable(false);
        txtNoT.setBackground(new java.awt.Color(255, 255, 255));
        txtNoT.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        txtNoT.setForeground(new java.awt.Color(0, 51, 51));
        txtNoT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNoT.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jPanel10.add(txtNoT, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 150, -1));

        lblNoB.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNoB.setForeground(new java.awt.Color(0, 51, 51));
        lblNoB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNoB.setText("Number of Titles");
        jPanel10.add(lblNoB, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 240, 30));

        jPanel9.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 240, 120));

        jPanel12.setBackground(new java.awt.Color(0, 51, 51));
        jPanel12.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        RoundedPanel jPanel12 = new RoundedPanel(30);
        jPanel12.setBackground(new Color(255, 255, 255));

        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNoB1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNoB1.setForeground(new java.awt.Color(0, 51, 51));
        lblNoB1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNoB1.setText("Total Books in Library");
        jPanel12.add(lblNoB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 240, -1));

        txtNoB.setEditable(false);
        txtNoB.setBackground(new java.awt.Color(255, 255, 255));
        txtNoB.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        txtNoB.setForeground(new java.awt.Color(0, 51, 51));
        txtNoB.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNoB.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtNoB.setOpaque(true);
        jPanel12.add(txtNoB, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 150, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICTURE_icon/books-rack.png"))); // NOI18N
        jPanel12.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jPanel9.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 240, 120));

        jPanel11.setBackground(new java.awt.Color(0, 51, 51));
        jPanel11.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        RoundedPanel jPanel11 = new RoundedPanel(30);
        jPanel11.setBackground(new Color(255, 255, 255));

        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNoR.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNoR.setForeground(new java.awt.Color(0, 51, 51));
        lblNoR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNoR.setText("Total Readers in Library");
        jPanel11.add(lblNoR, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 10, 230, -1));

        txtNoR.setEditable(false);
        txtNoR.setBackground(new java.awt.Color(255, 255, 255));
        txtNoR.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        txtNoR.setForeground(new java.awt.Color(0, 51, 51));
        txtNoR.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNoR.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtNoR.setOpaque(true);
        jPanel11.add(txtNoR, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 150, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICTURE_icon/reading4.png"))); // NOI18N
        jPanel11.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 60, -1));

        jPanel9.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 30, 240, 120));

        jPanel14.setBackground(new java.awt.Color(0, 51, 51));
        jPanel14.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        RoundedPanel jPanel14 = new RoundedPanel(30);
        jPanel14.setBackground(new Color(255, 255, 255));

        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNoR1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNoR1.setForeground(new java.awt.Color(0, 51, 51));
        lblNoR1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNoR1.setText("Total Readers Overdue");
        jPanel14.add(lblNoR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 10, 240, -1));

        txtNoOver.setEditable(false);
        txtNoOver.setBackground(new java.awt.Color(255, 255, 255));
        txtNoOver.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        txtNoOver.setForeground(new java.awt.Color(0, 51, 51));
        txtNoOver.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNoOver.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtNoOver.setOpaque(true);
        txtNoOver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoOverActionPerformed(evt);
            }
        });
        jPanel14.add(txtNoOver, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 150, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICTURE_icon/overdue.png"))); // NOI18N
        jPanel14.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 40, 70, -1));

        jPanel9.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 30, 240, 120));

        jPanel15.setBackground(new java.awt.Color(0, 51, 51));
        jPanel15.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        RoundedPanel jPanel15 = new RoundedPanel(30);
        jPanel15.setBackground(new Color(255, 255, 255));

        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNoR2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblNoR2.setForeground(new java.awt.Color(0, 51, 51));
        lblNoR2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNoR2.setText("Total Readers Borrowing Books");
        jPanel15.add(lblNoR2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 10, 240, -1));

        txtNoBR.setEditable(false);
        txtNoBR.setBackground(new java.awt.Color(255, 255, 255));
        txtNoBR.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        txtNoBR.setForeground(new java.awt.Color(0, 51, 51));
        txtNoBR.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNoBR.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtNoBR.setOpaque(true);
        txtNoBR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoBRActionPerformed(evt);
            }
        });
        jPanel15.add(txtNoBR, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 150, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICTURE_icon/borrow.png"))); // NOI18N
        jPanel15.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 40, 70, -1));

        jPanel9.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 30, 240, 120));

        jPanel7.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 320));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICTURE_icon/library2.png"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 0, 0, 0, new java.awt.Color(255, 255, 255)));
        jPanel7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 1300, 700));

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 700));

        jPanel3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 1300, -1));

        btnLOGOUT.setBackground(new java.awt.Color(0, 51, 51));
        btnLOGOUT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICTURE_icon/icons8_Exit_26px_2.png"))); // NOI18N
        btnLOGOUT.setText("Logout");
        btnLOGOUT.setColorHover(new java.awt.Color(204, 0, 51));
        btnLOGOUT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLOGOUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLOGOUTActionPerformed(evt);
            }
        });
        jPanel3.add(btnLOGOUT, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 660, 200, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1500, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMRActionPerformed
        ManageReaders MR = new ManageReaders();
        MR.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMRActionPerformed

    private void btnBBFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBBFActionPerformed
        BooksBorrowing BBF = new BooksBorrowing();
        BBF.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBBFActionPerformed

    private void btnMPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMPActionPerformed
        Penalty P = new Penalty();
        P.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMPActionPerformed

    private void btnLOGOUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLOGOUTActionPerformed

    }//GEN-LAST:event_btnLOGOUTActionPerformed

    private void btnMBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMBActionPerformed
        ManageBookss MB = new ManageBookss();
        MB.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnMBActionPerformed

    private void btnStatisticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatisticsActionPerformed
        Statistics S = new Statistics();
        S.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnStatisticsActionPerformed

    private void txtNoOverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoOverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoOverActionPerformed

    private void txtNoBRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoBRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoBRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSButtonHover btnBBF;
    private rojerusan.RSButtonHover btnLOGOUT;
    private rojerusan.RSButtonHover btnMB;
    private rojerusan.RSButtonHover btnMP;
    private rojerusan.RSButtonHover btnMR;
    private rojerusan.RSButtonHover btnStatistics;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblNoB;
    private javax.swing.JLabel lblNoB1;
    private javax.swing.JLabel lblNoR;
    private javax.swing.JLabel lblNoR1;
    private javax.swing.JLabel lblNoR2;
    private javax.swing.JTextField txtNoB;
    private javax.swing.JTextField txtNoBR;
    private javax.swing.JTextField txtNoOver;
    private javax.swing.JTextField txtNoR;
    private javax.swing.JTextField txtNoT;
    // End of variables declaration//GEN-END:variables
}
