/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframe;

/**
 *
 * @author HS
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnMR = new rojerusan.RSButtonHover();
        btnBBF = new rojerusan.RSButtonHover();
        btnMP = new rojerusan.RSButtonHover();
        btnMB = new rojerusan.RSButtonHover();
        btnMP1 = new rojerusan.RSButtonHover();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnLOGOUT = new rojerusan.RSButtonHover();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICTURE_icon/li4.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 41, -1));

        jPanel1.setBackground(new java.awt.Color(102, 102, 0));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 6, 3, 35));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("LIBRARY MANAGEMENT SYSTEM");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 15, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, 50));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setBackground(new java.awt.Color(102, 153, 255));
        jPanel13.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 0, 0, 0, new java.awt.Color(255, 255, 255)));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(102, 153, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICTURE_icon/home.png"))); // NOI18N
        jLabel4.setText("HOME PAGE");
        jLabel4.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 0, 0, 0, new java.awt.Color(255, 255, 255)));
        jPanel13.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 170, 50));

        jPanel4.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, -1));

        jPanel5.setBackground(new java.awt.Color(0, 51, 51));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DASHBOARD");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 140, 39));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 51, 200, -1));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICTURE_icon/home_24px.png"))); // NOI18N
        jLabel8.setText("HOME PAGE");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, -1, 39));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Features");
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 39));

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 96, 200, 39));

        btnMR.setBackground(new java.awt.Color(255, 255, 255));
        btnMR.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        btnMR.setForeground(new java.awt.Color(0, 51, 51));
        btnMR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICTURE_icon/book-reader.png"))); // NOI18N
        btnMR.setText("Manage  Readers");
        btnMR.setColorHover(new java.awt.Color(204, 0, 51));
        btnMR.setColorText(new java.awt.Color(0, 51, 51));
        btnMR.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMRActionPerformed(evt);
            }
        });
        jPanel4.add(btnMR, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 200, -1));

        btnBBF.setBackground(new java.awt.Color(255, 255, 255));
        btnBBF.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        btnBBF.setForeground(new java.awt.Color(0, 51, 51));
        btnBBF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICTURE_icon/online-survey.png"))); // NOI18N
        btnBBF.setText("Managing Borrow Slips");
        btnBBF.setColorHover(new java.awt.Color(204, 0, 51));
        btnBBF.setColorText(new java.awt.Color(0, 51, 51));
        btnBBF.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBBF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBBFActionPerformed(evt);
            }
        });
        jPanel4.add(btnBBF, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 200, -1));

        btnMP.setBackground(new java.awt.Color(255, 255, 255));
        btnMP.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        btnMP.setForeground(new java.awt.Color(0, 51, 51));
        btnMP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICTURE_icon/punishment.png"))); // NOI18N
        btnMP.setText("Managing Penalties");
        btnMP.setColorHover(new java.awt.Color(204, 0, 51));
        btnMP.setColorText(new java.awt.Color(0, 51, 51));
        btnMP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMPActionPerformed(evt);
            }
        });
        jPanel4.add(btnMP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 200, -1));

        btnMB.setBackground(new java.awt.Color(255, 255, 255));
        btnMB.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        btnMB.setForeground(new java.awt.Color(0, 51, 51));
        btnMB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICTURE_icon/knowledge.png"))); // NOI18N
        btnMB.setText("Manage Books");
        btnMB.setColorHover(new java.awt.Color(204, 0, 51));
        btnMB.setColorText(new java.awt.Color(0, 51, 51));
        btnMB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMBActionPerformed(evt);
            }
        });
        jPanel4.add(btnMB, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, -1, -1));

        btnMP1.setBackground(new java.awt.Color(255, 255, 255));
        btnMP1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        btnMP1.setForeground(new java.awt.Color(0, 51, 51));
        btnMP1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICTURE_icon/pie-chart.png"))); // NOI18N
        btnMP1.setText("Statistic");
        btnMP1.setColorHover(new java.awt.Color(204, 0, 51));
        btnMP1.setColorText(new java.awt.Color(0, 51, 51));
        btnMP1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMP1ActionPerformed(evt);
            }
        });
        jPanel4.add(btnMP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, -1, -1));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, -1));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 700));

        jPanel9.setBackground(new java.awt.Color(0, 51, 51));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 7, 3, 700));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICTURE_icon/library2.png"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 0, 0, 0, new java.awt.Color(255, 255, 255)));
        jPanel7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, -1, 700));

        jPanel3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 1300, -1));

        btnLOGOUT.setBackground(new java.awt.Color(0, 51, 51));
        btnLOGOUT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICTURE_icon/icons8_Exit_26px_2.png"))); // NOI18N
        btnLOGOUT.setText("Logout");
        btnLOGOUT.setColorHover(new java.awt.Color(204, 0, 51));
        btnLOGOUT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLOGOUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLOGOUTActionPerformed(evt);
            }
        });
        jPanel3.add(btnLOGOUT, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 660, 200, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1500, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMRActionPerformed
        ManageReaders MR = new ManageReaders();
        MR.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMRActionPerformed

    private void btnBBFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBBFActionPerformed
        BooksBorrowing BBF = new BooksBorrowing();
        BBF.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBBFActionPerformed

    private void btnMPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMPActionPerformed
        Penalty P = new Penalty();
        P.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMPActionPerformed

    private void btnLOGOUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLOGOUTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLOGOUTActionPerformed

    private void btnMBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMBActionPerformed
        ManageBookss MB = new ManageBookss();
        MB.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnMBActionPerformed

    private void btnMP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMP1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSButtonHover btnBBF;
    private rojerusan.RSButtonHover btnLOGOUT;
    private rojerusan.RSButtonHover btnMB;
    private rojerusan.RSButtonHover btnMP;
    private rojerusan.RSButtonHover btnMP1;
    private rojerusan.RSButtonHover btnMR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
