/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframe;

/**
 *
 * @author HS
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnMR = new rojerusan.RSButtonHover();
        btnBBF = new rojerusan.RSButtonHover();
        btnBD = new rojerusan.RSButtonHover();
        btnPF = new rojerusan.RSButtonHover();
        btnMB = new rojerusan.RSButtonHover();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        lbl_nofOfBooks = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        lbl_nofOfBooks1 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        lbl_nofOfBooks2 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();
        lbl_nofOfBooks5 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jPanel29 = new javax.swing.JPanel();
        lbl_nofOfBooks6 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnMR4 = new rojerusan.RSButtonHover();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_menu_48px_1.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 41, -1));

        jPanel1.setBackground(new java.awt.Color(102, 102, 0));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 6, 3, 35));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("LIBRARY MANAGEMENT SYSTEM");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 15, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, 50));

        jPanel3.setBackground(new java.awt.Color(102, 153, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(102, 153, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 51));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/24x24_home-silhouette-on-black-square-background_icon-icons.com_70471.png"))); // NOI18N
        jLabel4.setText("       HOME PAGE");
        jPanel13.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 180, 50));

        jPanel4.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, -1));

        jPanel5.setBackground(new java.awt.Color(102, 153, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/dashboard_24x24.png"))); // NOI18N
        jLabel5.setText("       DASHBOARD");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, 39));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 51, 210, -1));

        jPanel6.setBackground(new java.awt.Color(102, 153, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/home_24px.png"))); // NOI18N
        jLabel8.setText("HOME PAGE");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, -1, 39));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Features");
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 39));

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 96, 200, 39));

        btnMR.setBackground(new java.awt.Color(102, 153, 255));
        btnMR.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        btnMR.setForeground(new java.awt.Color(0, 51, 51));
        btnMR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/24x24 reader.png"))); // NOI18N
        btnMR.setText("Manage  Readers");
        btnMR.setColorHover(new java.awt.Color(204, 0, 51));
        btnMR.setColorText(new java.awt.Color(0, 51, 51));
        btnMR.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMRActionPerformed(evt);
            }
        });
        jPanel4.add(btnMR, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 200, 210, -1));

        btnBBF.setBackground(new java.awt.Color(102, 153, 255));
        btnBBF.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        btnBBF.setForeground(new java.awt.Color(0, 51, 51));
        btnBBF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/24x24_form_line_icon_235623.png"))); // NOI18N
        btnBBF.setText("Books Borrowing Form");
        btnBBF.setColorHover(new java.awt.Color(204, 0, 51));
        btnBBF.setColorText(new java.awt.Color(0, 51, 51));
        btnBBF.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBBF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBBFActionPerformed(evt);
            }
        });
        jPanel4.add(btnBBF, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 250, 210, -1));

        btnBD.setBackground(new java.awt.Color(102, 153, 255));
        btnBD.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        btnBD.setForeground(new java.awt.Color(0, 51, 51));
        btnBD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/24x24form_85828.png"))); // NOI18N
        btnBD.setText("Borrow Details");
        btnBD.setColorHover(new java.awt.Color(204, 0, 51));
        btnBD.setColorText(new java.awt.Color(0, 51, 51));
        btnBD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBDActionPerformed(evt);
            }
        });
        jPanel4.add(btnBD, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 300, 210, -1));

        btnPF.setBackground(new java.awt.Color(102, 153, 255));
        btnPF.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        btnPF.setForeground(new java.awt.Color(0, 51, 51));
        btnPF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/coins-stacks-money_icon-icons.com_56191.png"))); // NOI18N
        btnPF.setText("Penalty Fees");
        btnPF.setColorHover(new java.awt.Color(204, 0, 51));
        btnPF.setColorText(new java.awt.Color(0, 51, 51));
        btnPF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPFActionPerformed(evt);
            }
        });
        jPanel4.add(btnPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 350, 210, -1));

        btnMB.setBackground(new java.awt.Color(102, 153, 255));
        btnMB.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        btnMB.setForeground(new java.awt.Color(0, 51, 51));
        btnMB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/24x24_bookstack_libr_3024.png"))); // NOI18N
        btnMB.setText("    Manage Books");
        btnMB.setColorHover(new java.awt.Color(204, 0, 51));
        btnMB.setColorText(new java.awt.Color(0, 51, 51));
        btnMB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMBActionPerformed(evt);
            }
        });
        jPanel4.add(btnMB, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, -1));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, -1));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 700));

        jPanel9.setBackground(new java.awt.Color(0, 51, 51));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 3, 700));

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 10, new java.awt.Color(0, 51, 51)));
        jPanel15.setForeground(new java.awt.Color(255, 255, 255));
        jPanel15.setPreferredSize(new java.awt.Dimension(260, 1));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_nofOfBooks.setBackground(new java.awt.Color(255, 255, 255));
        lbl_nofOfBooks.setFont(new java.awt.Font("Segoe Pro Black", 0, 50)); // NOI18N
        lbl_nofOfBooks.setForeground(new java.awt.Color(255, 51, 51));
        lbl_nofOfBooks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Book_Shelf_50px.png"))); // NOI18N
        lbl_nofOfBooks.setText("100");
        jPanel15.add(lbl_nofOfBooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 147, -1));

        jPanel7.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 200, 120));

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 10, new java.awt.Color(0, 51, 51)));
        jPanel16.setPreferredSize(new java.awt.Dimension(260, 1));

        lbl_nofOfBooks1.setBackground(new java.awt.Color(102, 102, 102));
        lbl_nofOfBooks1.setFont(new java.awt.Font("Segoe Pro Black", 0, 50)); // NOI18N
        lbl_nofOfBooks1.setForeground(new java.awt.Color(255, 51, 51));
        lbl_nofOfBooks1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Book_Shelf_50px.png"))); // NOI18N
        lbl_nofOfBooks1.setText("10");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(lbl_nofOfBooks1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(lbl_nofOfBooks1)
                .addGap(25, 25, 25))
        );

        jPanel7.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 200, 120));

        jLabel26.setBackground(new java.awt.Color(102, 102, 102));
        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Borrowwed");
        jPanel7.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 110, 20));

        jLabel27.setBackground(new java.awt.Color(102, 102, 102));
        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Number Of Books");
        jPanel7.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 180, -1));

        jLabel28.setBackground(new java.awt.Color(102, 102, 102));
        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Nunber Of Readers");
        jPanel7.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 190, -1));

        jPanel25.setBackground(new java.awt.Color(255, 255, 255));
        jPanel25.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 10, new java.awt.Color(0, 51, 51)));
        jPanel25.setPreferredSize(new java.awt.Dimension(260, 1));
        jPanel25.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_nofOfBooks2.setBackground(new java.awt.Color(102, 102, 102));
        lbl_nofOfBooks2.setFont(new java.awt.Font("Segoe Pro Black", 0, 50)); // NOI18N
        lbl_nofOfBooks2.setForeground(new java.awt.Color(255, 51, 51));
        lbl_nofOfBooks2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Book_Shelf_50px.png"))); // NOI18N
        lbl_nofOfBooks2.setText("100");
        jPanel25.add(lbl_nofOfBooks2, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 28, 150, -1));

        jPanel7.add(jPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, 200, 120));

        jLabel24.setBackground(new java.awt.Color(102, 102, 102));
        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Nunber Of Books");
        jPanel7.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 168, -1));

        jPanel28.setBackground(new java.awt.Color(255, 255, 255));
        jPanel28.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 10, new java.awt.Color(0, 51, 51)));
        jPanel28.setPreferredSize(new java.awt.Dimension(260, 1));
        jPanel28.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_nofOfBooks5.setBackground(new java.awt.Color(102, 102, 102));
        lbl_nofOfBooks5.setFont(new java.awt.Font("Segoe Pro Black", 0, 50)); // NOI18N
        lbl_nofOfBooks5.setForeground(new java.awt.Color(255, 51, 51));
        lbl_nofOfBooks5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Book_Shelf_50px.png"))); // NOI18N
        lbl_nofOfBooks5.setText("10");
        jPanel28.add(lbl_nofOfBooks5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 26, 127, -1));

        jPanel7.add(jPanel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 60, 200, 120));

        jLabel31.setBackground(new java.awt.Color(102, 102, 102));
        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Number Of Late Readers");
        jPanel7.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, 240, -1));

        jPanel29.setBackground(new java.awt.Color(255, 255, 255));
        jPanel29.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 10, new java.awt.Color(0, 51, 51)));
        jPanel29.setPreferredSize(new java.awt.Dimension(260, 1));
        jPanel29.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_nofOfBooks6.setBackground(new java.awt.Color(102, 102, 102));
        lbl_nofOfBooks6.setFont(new java.awt.Font("Segoe Pro Black", 0, 50)); // NOI18N
        lbl_nofOfBooks6.setForeground(new java.awt.Color(255, 51, 51));
        lbl_nofOfBooks6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Book_Shelf_50px.png"))); // NOI18N
        lbl_nofOfBooks6.setText("1000");
        jPanel29.add(lbl_nofOfBooks6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 170, -1));

        jPanel7.add(jPanel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 60, 200, 120));

        jLabel32.setBackground(new java.awt.Color(102, 102, 102));
        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Penalities Cost ($)");
        jPanel7.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 10, 240, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/library2.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, -1, 700));

        jPanel3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 1300, -1));

        btnMR4.setBackground(new java.awt.Color(0, 51, 51));
        btnMR4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Exit_26px_2.png"))); // NOI18N
        btnMR4.setText("Logout");
        btnMR4.setColorHover(new java.awt.Color(204, 0, 51));
        btnMR4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMR4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMR4ActionPerformed(evt);
            }
        });
        jPanel3.add(btnMR4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 660, 200, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1500, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMRActionPerformed

    private void btnBBFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBBFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBBFActionPerformed

    private void btnBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBDActionPerformed

    private void btnPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPFActionPerformed

    private void btnMR4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMR4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMR4ActionPerformed

    private void btnMBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMBActionPerformed
        ManageBookss MB = new ManageBookss();
        MB.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnMBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSButtonHover btnBBF;
    private rojerusan.RSButtonHover btnBD;
    private rojerusan.RSButtonHover btnMB;
    private rojerusan.RSButtonHover btnMR;
    private rojerusan.RSButtonHover btnMR4;
    private rojerusan.RSButtonHover btnPF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lbl_nofOfBooks;
    private javax.swing.JLabel lbl_nofOfBooks1;
    private javax.swing.JLabel lbl_nofOfBooks2;
    private javax.swing.JLabel lbl_nofOfBooks5;
    private javax.swing.JLabel lbl_nofOfBooks6;
    // End of variables declaration//GEN-END:variables
}
